### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by ioannagkika** [zhuyr97/WGWS-Net#4]
Could you please upload the dataset_pairs_wRandomSample_ForAug3 file in the repository? The training_Setting1_wDP_Stage2.py file cannot run without this file. 

Also, could you upload the code for training your model using Settings 2 and 3?

**Comment by zhuyr97** [comment]
I have made minor revisions to the file 'training_Setting1_wDP_Stage2.py'.

To train the datasets for Settings 2/3 in Stage 2, you can still use the 'training_Setting1_wDP_Stage2.py' file. However, for setting 3, we read the training data in TXT format from another file located under the datasets folder.
