### ISSUE TITLE
about dataset_pairs_wRandomSample_Triplet

### ISSUE THREAD

**Issue by chensming** [zhuyr97/WGWS-Net#8]
Hi, you have done a good job. But there is one question that puzzles me： 

https://github.com/zhuyr97/WGWS-Net/blob/3583302dd8ba9adbfeb58debd007c25a50ac245e/training_Setting1_Stage1.py#L11

I can't find this file in directory 'datasets'. Do you  mean dataset_pairs_wRandomSample_Triplet_txt.py?

**Comment by zhuyr97** [comment]
yes!
