### ISSUE TITLE
about graph

### ISSUE THREAD

**Issue by aoe-wyb** [zhuyr97/WGWS-Net#9]
Hello, I'm very interested in your work and  like to know how to draw this graph.
![image](https://github.com/zhuyr97/WGWS-Net/assets/62412181/d7671c69-2015-46b8-921b-1b9088671517)

**Comment by zhuyr97** [comment]
Please give me your email. I would like to send it to you~

**Comment by aoe-wyb** [comment]
thanks.
email : ***@***.***





发自我的iPhone


------------------ Original ------------------
From: Yurui Zhu ***@***.***&gt;
Date: Fri,Nov 17,2023 1:09 AM
To: zhuyr97/WGWS-Net ***@***.***&gt;
Cc: aoe-wyb ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [zhuyr97/WGWS-Net] about graph (Issue #9)





 
Please give me your email. I would like to send it to you~

**Comment by aoe-wyb** [comment]
1394884511@qq.com

**Comment by zhuyr97** [comment]
Please check your email~

**Comment by Alice206** [comment]
Hello, I'm confused about this graph too, is it convenient to share it with me through 1425416575@qq.com? Thanks sincerely!
